### ISSUE TITLE
 multithreading in localsend?

### ISSUE THREAD

**Issue by ghost** [localsend/protocol#10]
Hello everyone!

I would like to know if it is possible to add a multithreading property that has the value: "true" - to inform when processing multiple file types. And when "false", when this option should be disabled. It is possible to add a multithreading property that has the value: "true" - to inform when processing multiple file types. And when "false", when this option should be disabled?

#### what is multithreading?
Multithreading is the mass execution of several threads in the same process. Threads, in turn, is a unit that originates independently in the execution of a software process or application.

#### why?
- Multitasking is a computer's ability to execute two or more concurrent programs. Multithreading makes multitasking possible when it breaks programs into smaller, executable threads. 
- Each thread has the programming elements needed to execute the main program, and the computer executes each thread one at a time.
- Currently processing localsend files doesn't look like multithreading.

#### how? "idea"
Here we have a json property called: "multithreading", this property has value: "true" or "false". The value: "true" - informs that the multihtread option is possible. The value: "false" - informs that the option in the device is false.
```json5
{
  "alias": "Nice Orange",
  "deviceModel": "Samsung", // nullable
  "deviceType": "mobile", // mobile | desktop | web
  "fingerprint": "random string",
  "announcement": true,
  "multithreading": true, // true | false
}
```

#### why a property in json?
This is similar when you install an emulator that asks if the pc has hyper-v or not. What I ask here is similar to the use case. It is necessary to evaluate whether the cell phone is old or not to support the localsend protocol. In that sense, having a json property makes this possible.

**Comment by Tienisto** [comment]
Hi, multithreading should already technically work (and it is also stated in the documentation). The reason why the official app does not use it is because it was not implemented yet.
