### ISSUE TITLE
web-authn with localsend?

### ISSUE THREAD

**Issue by ghost** [localsend/protocol#2]
Hi everyone.

*Would it be possible to authenticate devices through the browser with webauthn along with the local send protocol locally?*

**Comment by vincivermeer** [comment]
Hello @ghost!

This was answered here: 
- [add localsend-protocol-v3](https://github.com/localsend/protocol/pull/6)
- [add v2](https://github.com/localsend/protocol/pull/5), 
- [login authentication ways for localsend](https://github.com/localsend/protocol/issues/4)
- [web-authn with localsend?](https://github.com/localsend/localsend/discussions/102)
