### ISSUE TITLE
Clarification: What is `download API (5.2 and 5.3)` ?

### ISSUE THREAD

**Issue by nain-F49FF806** [localsend/protocol#25]
In the documentation for many messages it is mentioned

> "download": true, // if the download API (5.2 and 5.3) is active (optional, default: false)

What is download API (5.2 and 5.3) ?

I tried searching the app code for api of this verison number, but couldn't find anything.

**Comment by Tienisto** [comment]
It means that `POST /api/localsend/v2/prepare-download` (5.2) and `GET /api/localsend/v2/download` (5.3) are available

**Comment by nain-F49FF806** [comment]
Oh, so it's those endpoints and their describing section numbers!  
Thanks, I thought it was completely different interface (described elsewhere) and it's version numbers. :sweat_smile:

**Comment by nain-F49FF806** [comment]
Do you mind if I send a PR, with some edits to clarify sections / references?

**Comment by Tienisto** [comment]
Sure
