### ISSUE TITLE
create RFC draft to localsend(protocol)

### ISSUE THREAD

**Issue by vincivermeer** [localsend/protocol#8]
Hello everyone!

I would like to understand more deeply how the localsend protocol works. A good part of the protocols is in some RFC, example
- here: [ietf\standards\rfcs](https://www.ietf.org/standards/rfcs/) or
- here [rfc-editor.org](https://www.rfc-editor.org/) or
- here [datatracker.ietf.org](https://datatracker.ietf.org/)

But... I would like to know if you all have already thought about adding the localsend protocol in the RFC?

note: I didn't find much information about the localsend protocol in these links I mentioned above.
 So, If anyone can clarify these doubts I would be happy for the feedback.

**Comment by Tienisto** [comment]
Hi,
The README should be enough to implement clients that are LocalSend compatible. A specification would make this project more serious but this is currently out of scope.
